In [19]:
import numpy as np
import pandas as pd

In [20]:
dfprop = pd.read_csv('properties.csv').copy()
dfprop.head()

,Unnamed: 0,﻿id,building,date_sale,type,property#,area,price,status,customerid
0,0,1030,1,11/1/2005,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1,1029,1,10/1/2005,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2,2002,2,7/1/2007,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,3,2031,2,12/1/2007,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,4,1049,1,11/1/2004,Apartment,49,1375.45,"$467,083.31",Sold,C0014

In [21]:
dfprop.columns = dfprop.columns.str.strip().str.replace('\ufeff', '')

In [22]:
dfprop = dfprop.drop(['Unnamed: 0'], axis = 1)
dfprop.head()

,id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,11/1/2005,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1029,1,10/1/2005,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2002,2,7/1/2007,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,2031,2,12/1/2007,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,1049,1,11/1/2004,Apartment,49,1375.45,"$467,083.31",Sold,C0014

In [23]:
dfprop.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          267 non-null    int64
 1   building    267 non-null    int64
 2   date_sale   267 non-null    str
 3   type        267 non-null    str
 4   property#   267 non-null    int64
 5   area        267 non-null    float64
 6   price       267 non-null    str
 7   status      267 non-null    str
 8   customerid  195 non-null    str
dtypes: float64(1), int64(3), str(5)
memory usage: 18.9 KB

In [24]:
dfprop['customerid'].nunique()

162

In [25]:
dfprop['customerid'].count()

np.int64(195)

In [26]:
dfprop.isna().sum()

id             0
building       0
date_sale      0
type           0
property#      0
area           0
price          0
status         0
customerid    72
dtype: int64

In [27]:
dfprop['status'].value_counts()

status
 Sold     195
-          72
Name: count, dtype: int64

In [28]:
dfprop['status'].isna().sum()

np.int64(0)

In [29]:
dfprop['status'].tail(20)

247    -
248    -
249    -
250    -
251    -
252    -
253    -
254    -
255    -
256    -
257    -
258    -
259    -
260    -
261    -
262    -
263    -
264    -
265    -
266    -
Name: status, dtype: str

In [30]:
dfprop['status'] = dfprop['status'].replace('-', 'Unknown')

In [31]:
dfprop.tail(40)

,id,building,date_sale,type,property#,area,price,status,customerid
227,4033,4,#NUM!,Apartment,33,789.25,"$228,872.91",Unknown,NaN
228,4034,4,#NUM!,Apartment,34,794.52,"$208,655.67",Unknown,NaN
229,4036,4,#NUM!,Apartment,36,1111.72,"$322,952.56",Unknown,NaN
230,4039,4,#NUM!,Apartment,39,785.48,"$216,826.00",Unknown,NaN
231,4044,4,#NUM!,Apartment,44,1058.25,"$298,730.40",Unknown,NaN
232,4046,4,#NUM!,Apartment,46,791.72,"$230,495.01",Unknown,NaN
233,4048,4,#NUM!,Apartment,48,1068.58,"$346,048.04",Unknown,NaN
234,4049,4,#NUM!,Apartment,49,1325.31,"$377,043.60",Unknown,NaN
235,5002,5,#NUM!,Apartment,2,1273.88,"$413,761.71",Unknown,NaN
236,5003,5,#NUM!,Apartment,3,798.50,"$212,644.39",Unknown,NaN
237,5004,5,#NUM!,Apartment,4,798.50,"$250,415.38",Unknown,NaN
238,5005,5,#NUM!,Apartment,5,798.50,"$219,252.89",Unknown,NaN
239,5006,5,#NUM!,Apartment,6,1058.25,"$264,011.70",Unknown,NaN
240,5007,5,#NUM!,Apartment,7,618.16,"$211,406.87",Unknown,NaN
241,5008,5,#NUM!,Apartment,8,1273.88,"$396,330.29",Unknown,NaN
242,5009,5,#NUM!,Apartment,9,798.50,"$227,072.88",Unknown,NaN
243,5010,5,#NUM!,Apartment,10,798.50,"$276,323.87",Unknown,NaN
244,5011,5,#NUM!,Apartment,11,798.50,"$230,943.38",Unknown,NaN
245,5012,5,#NUM!,Apartment,12,1058.25,"$315,382.11",Unknown,NaN
246,5014,5,#NUM!,Apartment,14,1273.55,"$372,016.56",Unknown,NaN
247,5015,5,#NUM!,Apartment,15,798.50,"$237,680.88",Unknown,NaN
248,5016,5,#NUM!,Apartment,16,798.50,"$234,032.88",Unknown,NaN
249,5017,5,#NUM!,Apartment,17,798.28,"$273,165.58",Unknown,NaN
250,5018,5,#NUM!,Apartment,18,1057.92,"$271,227.49",Unknown,NaN
251,5020,5,#NUM!,Apartment,20,1273.55,"$349,865.22",Unknown,NaN
252,5025,5,#NUM!,Apartment,25,618.16,"$199,730.73",Unknown,NaN
253,5026,5,#NUM!,Apartment,26,1273.55,"$338,482.45",Unknown,NaN
254,5030,5,#NUM!,Apartment,30,1057.92,"$351,304.58",Unknown,NaN
255,5032,5,#NUM!,Apartment,32,1273.55,"$338,472.13",Unknown,NaN
256,5034,5,#NUM!,Apartment,34,798.28,"$212,916.36",Unknown,NaN
257,5036,5,#NUM!,Apartment,36,1057.92,"$308,660.80",Unknown,NaN
258,5037,5,#NUM!,Apartment,37,606.33,"$147,343.69",Unknown,NaN
259,5038,5,#NUM!,Apartment,38,1273.55,"$448,574.67",Unknown,NaN
260,5041,5,#NUM!,Apartment,41,798.28,"$255,337.90",Unknown,NaN
261,5043,5,#NUM!,Apartment,43,598.58,"$175,773.59",Unknown,NaN
262,5044,5,#NUM!,Apartment,44,1238.58,"$322,610.74",Unknown,NaN
263,5047,5,#NUM!,Apartment,47,794.52,"$279,191.26",Unknown,NaN
264,5048,5,#NUM!,Apartment,48,1013.27,"$287,996.53",Unknown,NaN
265,5050,5,#NUM!,Apartment,50,1074.71,"$365,868.78",Unknown,NaN
266,5051,5,#NUM!,Apartment,51,789.25,"$199,216.40",Unknown,NaN

In [32]:
dfprop['date_sale'] = dfprop['date_sale'].replace('#NUM!', 'Unknown')
dfprop['date_sale'].tail(5)

262    Unknown
263    Unknown
264    Unknown
265    Unknown
266    Unknown
Name: date_sale, dtype: str

In [33]:
# Convert to datetime, 'unknown' becomes NaT
dfprop['date_sale'] = pd.to_datetime(dfprop['date_sale'], errors='coerce')

In [34]:
dfcust = pd.read_csv('dfcust_cleaned.csv').copy()
dfcust.head()

,Unnamed: 0,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,0,C0110,Kareem Liu,57,1,F,1,1,1,4,1,Website
1,1,C0010,Trystan Oconnor,63,1,M,1,1,1,1,0,Website
2,2,C0132,Kale Gay,66,1,M,1,1,1,4,1,Agency
3,3,C0137,Russell Gross,66,1,M,1,1,1,5,0,Website
4,4,C0174,Marleez Co,62,0,Unknown,1,1,0,5,0,Website

In [35]:
dfprop['customerid'].equals(dfcust['customerid'])

False

In [36]:
dfprop['customerid'].duplicated().sum()

np.int64(104)

In [37]:
dfcust['customerid'].nunique()

162

In [38]:
pd.DataFrame(dfcust)

dfprop['customerid'].isin(dfcust['customerid']).sum()

np.int64(0)

In [39]:
dfprop['customerid'].dtype

In [40]:
dfcust['customerid'].dtype

In [41]:
dfcust['customerid'].to_list

<bound method IndexOpsMixin.tolist of 0      C0110
1      C0010
2      C0132
3      C0137
4      C0174
       ...
157    C0170
158    C0138
159    C0113
160    C0147
161    C0133
Name: customerid, Length: 162, dtype: str>

In [42]:
dfprop['customerid'].head(30)

0      C0028
1      C0027
2      C0112
3      C0160
4      C0014
5      C0125
6      C0125
7      C0166
8      C0034
9      C0170
10     C0009
11     C0041
12     C0057
13     C0061
14     C0089
15     C0159
16     C0171
17     C0042
18     C0093
19     C0093
20     C0051
21     C0064
22     C0064
23     C0128
24     C0019
25     C0037
26     C0127
27     C0018
28     C0040
29     C0080
Name: customerid, dtype: str

In [43]:
dfprop.head(10)

,id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,2005-11-01,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1029,1,2005-10-01,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2002,2,2007-07-01,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,2031,2,2007-12-01,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,1049,1,2004-11-01,Apartment,49,1375.45,"$467,083.31",Sold,C0014
5,3011,3,2007-09-01,Apartment,11,675.19,"$203,491.85",Sold,C0125
6,3026,3,2007-09-01,Apartment,26,670.89,"$212,520.83",Sold,C0125
7,3023,3,2008-01-01,Apartment,23,720.81,"$198,591.85",Sold,C0166
8,1031,1,2006-06-01,Apartment,31,782.25,"$265,467.68",Sold,C0034
9,4023,4,2006-03-01,Apartment,23,794.52,"$235,633.26",Sold,C0170

In [44]:
dfprop.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          267 non-null    int64
 1   building    267 non-null    int64
 2   date_sale   195 non-null    datetime64[us]
 3   type        267 non-null    str
 4   property#   267 non-null    int64
 5   area        267 non-null    float64
 6   price       267 non-null    str
 7   status      267 non-null    str
 8   customerid  195 non-null    str
dtypes: datetime64[us](1), float64(1), int64(3), str(4)
memory usage: 18.9 KB

In [45]:
dfprop['status'].unique()

<StringArray>
[' Sold ', 'Unknown']
Length: 2, dtype: str

In [46]:
dfprop['status'] = np.where(dfprop['status'] == ' Sold ', 1, 0)
dfprop.head()

,id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,2005-11-01,Apartment,30,743.09,"$246,172.68",1,C0028
1,1029,1,2005-10-01,Apartment,29,756.21,"$246,331.90",1,C0027
2,2002,2,2007-07-01,Apartment,2,587.28,"$209,280.91",1,C0112
3,2031,2,2007-12-01,Apartment,31,1604.75,"$452,667.01",1,C0160
4,1049,1,2004-11-01,Apartment,49,1375.45,"$467,083.31",1,C0014

In [59]:
dfprop.tail()

,id,building,date_sale,type,property#,area,price,status,customerid
262,5044,5,NaT,Apartment,44,1238.58,"$322,610.74",0,NaN
263,5047,5,NaT,Apartment,47,794.52,"$279,191.26",0,NaN
264,5048,5,NaT,Apartment,48,1013.27,"$287,996.53",0,NaN
265,5050,5,NaT,Apartment,50,1074.71,"$365,868.78",0,NaN
266,5051,5,NaT,Apartment,51,789.25,"$199,216.40",0,NaN

In [60]:
dfprop['status'].sum()

np.int64(195)

In [49]:
dfprop['property#'].nunique()

59

In [50]:
dfprop['id'].nunique()

240

In [51]:
dfprop['id'].value_counts()

id
4023    2
1047    2
5051    2
3029    2
3031    2
       ..
5038    1
5043    1
5044    1
5047    1
5048    1
Name: count, Length: 240, dtype: int64

In [52]:
dfprop['id'].duplicated().sum()

np.int64(27)

In [53]:
dfprop['customerid'] = dfprop['customerid'].replace('','None')
dfprop.head()

,id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,2005-11-01,Apartment,30,743.09,"$246,172.68",1,C0028
1,1029,1,2005-10-01,Apartment,29,756.21,"$246,331.90",1,C0027
2,2002,2,2007-07-01,Apartment,2,587.28,"$209,280.91",1,C0112
3,2031,2,2007-12-01,Apartment,31,1604.75,"$452,667.01",1,C0160
4,1049,1,2004-11-01,Apartment,49,1375.45,"$467,083.31",1,C0014

In [54]:
dfprop.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          267 non-null    int64
 1   building    267 non-null    int64
 2   date_sale   195 non-null    datetime64[us]
 3   type        267 non-null    str
 4   property#   267 non-null    int64
 5   area        267 non-null    float64
 6   price       267 non-null    str
 7   status      267 non-null    int64
 8   customerid  195 non-null    str
dtypes: datetime64[us](1), float64(1), int64(4), str(3)
memory usage: 18.9 KB

In [55]:
dfprop['type'].unique()

<StringArray>
['Apartment', 'Office']
Length: 2, dtype: str

In [115]:
dfprop['type'] = np.where(dfprop['type'] == 'Apartment', 1, 0)
dfprop.head(3)

,id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,2005-11-01,1,30,743.09,"$246,172.68",1,C0028
1,1029,1,2005-10-01,1,29,756.21,"$246,331.90",1,C0027
2,2002,2,2007-07-01,1,2,587.28,"$209,280.91",1,C0112

In [56]:
dfprop_columns_reordered = ['customerid', 'id','building', 'date_sale', 'type','property#', 'area', 'price', 'status']
dfprop1 = dfprop
dfprop1 = dfprop1[dfprop_columns_reordered]
dfprop1.tail(15)

,customerid,id,building,date_sale,type,property#,area,price,status
252,NaN,5025,5,NaT,Apartment,25,618.16,"$199,730.73",0
253,NaN,5026,5,NaT,Apartment,26,1273.55,"$338,482.45",0
254,NaN,5030,5,NaT,Apartment,30,1057.92,"$351,304.58",0
255,NaN,5032,5,NaT,Apartment,32,1273.55,"$338,472.13",0
256,NaN,5034,5,NaT,Apartment,34,798.28,"$212,916.36",0
257,NaN,5036,5,NaT,Apartment,36,1057.92,"$308,660.80",0
258,NaN,5037,5,NaT,Apartment,37,606.33,"$147,343.69",0
259,NaN,5038,5,NaT,Apartment,38,1273.55,"$448,574.67",0
260,NaN,5041,5,NaT,Apartment,41,798.28,"$255,337.90",0
261,NaN,5043,5,NaT,Apartment,43,598.58,"$175,773.59",0
262,NaN,5044,5,NaT,Apartment,44,1238.58,"$322,610.74",0
263,NaN,5047,5,NaT,Apartment,47,794.52,"$279,191.26",0
264,NaN,5048,5,NaT,Apartment,48,1013.27,"$287,996.53",0
265,NaN,5050,5,NaT,Apartment,50,1074.71,"$365,868.78",0
266,NaN,5051,5,NaT,Apartment,51,789.25,"$199,216.40",0

In [58]:
dfprop1.to_csv('dfprop_cleaned2.csv')