In [1]:
import numpy as np
import pandas as pd

In [2]:
dfcust = pd.read_csv('customers.csv').copy()
dfcust.head()

,Unnamed: 0,﻿customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,0,C0110,Individual,Kareem,Liu,5/11/1968,F,USA,California,Home,4,Yes,Website
1,1,C0010,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,2,C0132,Individual,Kale,Gay,4/7/1959,M,USA,California,Home,4,Yes,Agency
3,3,C0137,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,4,C0174,Company,Marleez,Co,NaN,NaN,USA,California,Investment,5,No,Website

In [3]:
dfprop = pd.read_csv('properties.csv').copy()
dfprop.head()

,Unnamed: 0,﻿id,building,date_sale,type,property#,area,price,status,customerid
0,0,1030,1,11/1/2005,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1,1029,1,10/1/2005,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2,2002,2,7/1/2007,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,3,2031,2,12/1/2007,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,4,1049,1,11/1/2004,Apartment,49,1375.45,"$467,083.31",Sold,C0014

In [4]:
dfcust.describe()

       Unnamed: 0  deal_satisfaction
count  162.000000         162.000000
mean    80.500000           3.456790
std     46.909487           1.333276
min      0.000000           1.000000
25%     40.250000           3.000000
50%     80.500000           4.000000
75%    120.750000           5.000000
max    161.000000           5.000000

In [5]:
dfcust.isna().sum()

Unnamed: 0           0
﻿customerid          0
entity               0
name                 0
surname              0
birth_date           7
sex                  7
country              0
state                8
purpose              0
deal_satisfaction    0
mortgage             0
source               0
dtype: int64

In [6]:
dfprop.isna().sum()

Unnamed: 0     0
﻿id            0
building       0
date_sale      0
type           0
property#      0
area           0
price          0
status         0
customerid    72
dtype: int64

In [7]:
dfcust.columns

Index(['Unnamed: 0', '﻿customerid', 'entity', 'name', 'surname', 'birth_date',
       'sex', 'country', 'state', 'purpose', 'deal_satisfaction', 'mortgage',
       'source'],
      dtype='object')

In [8]:
dfcust.columns = dfcust.columns.str.strip().str.replace('\ufeff', '')

In [9]:
dfcust['customerid']

0      C0110
1      C0010
2      C0132
3      C0137
4      C0174
       ...
157    C0170
158    C0138
159    C0113
160    C0147
161    C0133
Name: customerid, Length: 162, dtype: object

In [10]:

dfcust.columns.values

array(['Unnamed: 0', 'customerid', 'entity', 'name', 'surname',
       'birth_date', 'sex', 'country', 'state', 'purpose',
       'deal_satisfaction', 'mortgage', 'source'], dtype=object)

In [11]:
dfcust = dfcust.drop(['Unnamed: 0'], axis = 1)

In [12]:
dfcust.columns.values

array(['customerid', 'entity', 'name', 'surname', 'birth_date', 'sex',
       'country', 'state', 'purpose', 'deal_satisfaction', 'mortgage',
       'source'], dtype=object)

In [13]:
dfcust['full_name'] = dfcust['name'] + ' ' + dfcust['surname']
dfcust.head()

,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name
0,C0110,Individual,Kareem,Liu,5/11/1968,F,USA,California,Home,4,Yes,Website,Kareem Liu
1,C0010,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website,Trystan Oconnor
2,C0132,Individual,Kale,Gay,4/7/1959,M,USA,California,Home,4,Yes,Agency,Kale Gay
3,C0137,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website,Russell Gross
4,C0174,Company,Marleez,Co,NaN,NaN,USA,California,Investment,5,No,Website,Marleez Co

In [14]:
dfcust = dfcust.drop(columns=['name', 'surname'])
dfcust

,customerid,entity,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name
0,C0110,Individual,5/11/1968,F,USA,California,Home,4,Yes,Website,Kareem Liu
1,C0010,Individual,11/26/1962,M,USA,California,Home,1,No,Website,Trystan Oconnor
2,C0132,Individual,4/7/1959,M,USA,California,Home,4,Yes,Agency,Kale Gay
3,C0137,Individual,11/25/1959,M,USA,California,Home,5,No,Website,Russell Gross
4,C0174,Company,NaN,NaN,USA,California,Investment,5,No,Website,Marleez Co
...,...,...,...,...,...,...,...,...,...,...,...
157,C0170,Individual,12/3/1979,F,USA,Virginia,Investment,3,Yes,Agency,Emmy Singh
158,C0138,Individual,4/14/1942,M,USA,California,Home,3,No,Website,Colin Campos
159,C0113,Individual,6/11/1959,F,USA,California,Home,4,No,Website,Anya Stephenson
160,C0147,Individual,11/10/1951,M,USA,California,Home,5,No,Website,Parker Poole
161,C0133,Individual,9/15/1953,M,USA,California,Home,4,No,Website,Ivan Bright

In [15]:
dfcust.dtypes

customerid           object
entity               object
birth_date           object
sex                  object
country              object
state                object
purpose              object
deal_satisfaction     int64
mortgage             object
source               object
full_name            object
dtype: object

In [16]:
dfcust['entity'].unique()

array(['Individual', 'Company'], dtype=object)

In [17]:
entity_bool_columns = pd.get_dummies(dfcust['entity'], drop_first = True, dtype = int)
entity_bool_columns

     Individual
0             1
1             1
2             1
3             1
4             0
..          ...
157           1
158           1
159           1
160           1
161           1

[162 rows x 1 columns]

In [18]:
dfcust['entity'] = entity_bool_columns.iloc[:, 0]
dfcust.head()

,customerid,entity,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name
0,C0110,1,5/11/1968,F,USA,California,Home,4,Yes,Website,Kareem Liu
1,C0010,1,11/26/1962,M,USA,California,Home,1,No,Website,Trystan Oconnor
2,C0132,1,4/7/1959,M,USA,California,Home,4,Yes,Agency,Kale Gay
3,C0137,1,11/25/1959,M,USA,California,Home,5,No,Website,Russell Gross
4,C0174,0,NaN,NaN,USA,California,Investment,5,No,Website,Marleez Co

In [19]:
dfcust['mortgage'].unique()

array(['Yes', 'No'], dtype=object)

In [20]:
dfcust['mortgage'] = pd.get_dummies(dfcust['mortgage'], drop_first=True, dtype=int)
dfcust.head(3)

,customerid,entity,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name
0,C0110,1,5/11/1968,F,USA,California,Home,4,1,Website,Kareem Liu
1,C0010,1,11/26/1962,M,USA,California,Home,1,0,Website,Trystan Oconnor
2,C0132,1,4/7/1959,M,USA,California,Home,4,1,Agency,Kale Gay

In [21]:
dfcust['country'].unique()

array(['USA', 'USA ', 'Canada', 'Germany', 'Belgium', 'Mexico', 'Russia',
       'UK', 'Denmark'], dtype=object)

In [22]:
dfcust['country'].value_counts()

country
USA        146
USA          4
Russia       4
UK           2
Belgium      2
Germany      1
Canada       1
Mexico       1
Denmark      1
Name: count, dtype: int64

In [23]:
dfcust['country'] = dfcust['country'].str.strip()
dfcust['country'].value_counts()

country
USA        150
Russia       4
UK           2
Belgium      2
Germany      1
Canada       1
Mexico       1
Denmark      1
Name: count, dtype: int64

In [24]:
dfcust['country'] = np.where(dfcust['country'] == 'USA', 1, 0)
dfcust['country'].unique()

array([1, 0])

In [25]:
dfcust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         162 non-null    object
 1   entity             162 non-null    int64
 2   birth_date         155 non-null    object
 3   sex                155 non-null    object
 4   country            162 non-null    int64
 5   state              154 non-null    object
 6   purpose            162 non-null    object
 7   deal_satisfaction  162 non-null    int64
 8   mortgage           162 non-null    int64
 9   source             162 non-null    object
 10  full_name          162 non-null    object
dtypes: int64(4), object(7)
memory usage: 14.1+ KB

In [26]:
dfcust['state'].unique()

array(['California', nan, 'Oregon', 'Arizona', 'Nevada', 'Colorado',
       'Utah', 'Virginia', 'Wyoming', 'Kansas'], dtype=object)

In [27]:
dfcust['state'].value_counts()

state
California    100
Nevada         14
Colorado       11
Arizona        10
Oregon          9
Utah            5
Virginia        3
Wyoming         1
Kansas          1
Name: count, dtype: int64

In [28]:
dfcust['state'] = dfcust['state'].fillna('Other')
dfcust['state'] = (dfcust['state'] == 'California').astype(int)
dfcust.head()

,customerid,entity,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name
0,C0110,1,5/11/1968,F,1,1,Home,4,1,Website,Kareem Liu
1,C0010,1,11/26/1962,M,1,1,Home,1,0,Website,Trystan Oconnor
2,C0132,1,4/7/1959,M,1,1,Home,4,1,Agency,Kale Gay
3,C0137,1,11/25/1959,M,1,1,Home,5,0,Website,Russell Gross
4,C0174,0,NaN,NaN,1,1,Investment,5,0,Website,Marleez Co

In [29]:
dfcust['state'].value_counts()

state
1    100
0     62
Name: count, dtype: int64

In [30]:
dfcust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         162 non-null    object
 1   entity             162 non-null    int64
 2   birth_date         155 non-null    object
 3   sex                155 non-null    object
 4   country            162 non-null    int64
 5   state              162 non-null    int64
 6   purpose            162 non-null    object
 7   deal_satisfaction  162 non-null    int64
 8   mortgage           162 non-null    int64
 9   source             162 non-null    object
 10  full_name          162 non-null    object
dtypes: int64(5), object(6)
memory usage: 14.1+ KB

In [31]:
dfcust['birth_date'] = pd.to_datetime(dfcust['birth_date'], errors='coerce')
dfcust['birth_date'].head()

0   1968-05-11
1   1962-11-26
2   1959-04-07
3   1959-11-25
4          NaT
Name: birth_date, dtype: datetime64[ns]

In [32]:
today = pd.Timestamp.today()
dfcust['age'] = (today - dfcust['birth_date']).dt.days / 365.25
dfcust['age'].head()

0    57.744011
1    63.200548
2    66.839151
3    66.203970
4          NaN
Name: age, dtype: float64

In [33]:
dfcust['age'] = dfcust['age'].fillna(dfcust['age'].median())
dfcust['age'] = dfcust['age'].astype(int)
dfcust.head()

,customerid,entity,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name,age
0,C0110,1,1968-05-11,F,1,1,Home,4,1,Website,Kareem Liu,57
1,C0010,1,1962-11-26,M,1,1,Home,1,0,Website,Trystan Oconnor,63
2,C0132,1,1959-04-07,M,1,1,Home,4,1,Agency,Kale Gay,66
3,C0137,1,1959-11-25,M,1,1,Home,5,0,Website,Russell Gross,66
4,C0174,0,NaT,NaN,1,1,Investment,5,0,Website,Marleez Co,62

In [34]:
dfcust = dfcust.drop(columns=['birth_date'])
dfcust_cleaned = dfcust.copy()

In [35]:
dfcust_cleaned.head()

,customerid,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,full_name,age
0,C0110,1,F,1,1,Home,4,1,Website,Kareem Liu,57
1,C0010,1,M,1,1,Home,1,0,Website,Trystan Oconnor,63
2,C0132,1,M,1,1,Home,4,1,Agency,Kale Gay,66
3,C0137,1,M,1,1,Home,5,0,Website,Russell Gross,66
4,C0174,0,NaN,1,1,Investment,5,0,Website,Marleez Co,62

In [36]:
dfcust_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         162 non-null    object
 1   entity             162 non-null    int64
 2   sex                155 non-null    object
 3   country            162 non-null    int64
 4   state              162 non-null    int64
 5   purpose            162 non-null    object
 6   deal_satisfaction  162 non-null    int64
 7   mortgage           162 non-null    int64
 8   source             162 non-null    object
 9   full_name          162 non-null    object
 10  age                162 non-null    int64
dtypes: int64(6), object(5)
memory usage: 14.1+ KB

In [37]:
dfcust.columns.values

array(['customerid', 'entity', 'sex', 'country', 'state', 'purpose',
       'deal_satisfaction', 'mortgage', 'source', 'full_name', 'age'],
      dtype=object)

In [38]:
dfcust_columns_reordered = ['customerid', 'full_name', 'age', 'entity', 'sex', 'country',
                            'state', 'purpose',
                            'deal_satisfaction', 'mortgage', 'source']
dfcust_cleaned = dfcust_cleaned[dfcust_columns_reordered]
dfcust_cleaned.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,C0110,Kareem Liu,57,1,F,1,1,Home,4,1,Website
1,C0010,Trystan Oconnor,63,1,M,1,1,Home,1,0,Website
2,C0132,Kale Gay,66,1,M,1,1,Home,4,1,Agency
3,C0137,Russell Gross,66,1,M,1,1,Home,5,0,Website
4,C0174,Marleez Co,62,0,NaN,1,1,Investment,5,0,Website

In [39]:
dfcust_cleaned['purpose'].value_counts()

purpose
Home          112
Investment     50
Name: count, dtype: int64

In [40]:
dfcust_cleaned['purpose'] = np.where(dfcust_cleaned['purpose'] == 'Home', 1, 0)
dfcust_cleaned['purpose'].unique()

array([1, 0])

In [41]:
dfcust_cleaned.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,C0110,Kareem Liu,57,1,F,1,1,1,4,1,Website
1,C0010,Trystan Oconnor,63,1,M,1,1,1,1,0,Website
2,C0132,Kale Gay,66,1,M,1,1,1,4,1,Agency
3,C0137,Russell Gross,66,1,M,1,1,1,5,0,Website
4,C0174,Marleez Co,62,0,NaN,1,1,0,5,0,Website

In [42]:
dfcust_cleaned['sex'] = dfcust_cleaned['sex'].fillna('Unknown')
dfcust_cleaned['sex'].value_counts()

sex
M          87
F          68
Unknown     7
Name: count, dtype: int64

In [43]:
dfcust_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         162 non-null    object
 1   full_name          162 non-null    object
 2   age                162 non-null    int64
 3   entity             162 non-null    int64
 4   sex                162 non-null    object
 5   country            162 non-null    int64
 6   state              162 non-null    int64
 7   purpose            162 non-null    int64
 8   deal_satisfaction  162 non-null    int64
 9   mortgage           162 non-null    int64
 10  source             162 non-null    object
dtypes: int64(7), object(4)
memory usage: 14.1+ KB

In [44]:
dfcust_cleaned.head(15)

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,C0110,Kareem Liu,57,1,F,1,1,1,4,1,Website
1,C0010,Trystan Oconnor,63,1,M,1,1,1,1,0,Website
2,C0132,Kale Gay,66,1,M,1,1,1,4,1,Agency
3,C0137,Russell Gross,66,1,M,1,1,1,5,0,Website
4,C0174,Marleez Co,62,0,Unknown,1,1,0,5,0,Website
5,C0088,Yurem Wright,68,1,M,1,1,1,3,1,Website
6,C0079,Xavier Faulkner,78,1,M,0,0,0,5,0,Website
7,C0149,Kayden Olsen,56,1,F,1,1,1,5,0,Website
8,C0064,Joaquin Mullins,50,1,M,1,1,0,5,0,Agency
9,C0068,Nicolas Navarro,59,1,M,1,0,0,3,0,Agency
10,C0006,Laci Guerra,69,1,F,1,1,1,2,1,Website
11,C0055,Kylax Co,62,0,Unknown,1,1,0,5,0,Website
12,C0016,Harley Lucero,63,1,M,1,1,1,1,1,Website
13,C0121,Esther Co,62,0,Unknown,1,1,1,3,1,Website
14,C0074,Jaylynn Hickman,84,1,F,1,1,1,5,0,Client

In [45]:
dfcust_cleaned.isna().sum()

customerid           0
full_name            0
age                  0
entity               0
sex                  0
country              0
state                0
purpose              0
deal_satisfaction    0
mortgage             0
source               0
dtype: int64

In [46]:
dfcust_cleaned.to_csv('dfcust_cleaned.csv')