In [1]:
import numpy as np
import pandas as pd

In [2]:
dfmerged = pd.read_csv('real-state-data.csv').copy()
dfmerged.head()

,Unnamed: 0,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
0,0,C0001,Kamd Co,62.0,0.0,Unknown,1.0,1.0,0.0,5.0,0.0,Agency,1005,1,2004-03-01,Office,5,410.71,"$117,564.07",1
1,1,C0002,Jack Anderson,78.0,1.0,M,1.0,1.0,0.0,5.0,1.0,Website,1002,1,2004-03-01,Office,2,1238.58,"$410,932.67",1
2,2,C0003,Avah Huang,77.0,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1044,1,2004-06-01,Apartment,44,827.87,"$229,464.71",1
3,3,C0004,Nora Lynch,77.0,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1043,1,2004-06-01,Apartment,43,1160.36,"$377,313.56",1
4,4,C0005,Rodolfo Gibson,89.0,1.0,M,1.0,0.0,1.0,2.0,1.0,Website,1033,1,2004-08-01,Apartment,33,1434.09,"$412,856.56",1

In [3]:
dfmerged = dfmerged.drop(columns = ['Unnamed: 0'], axis = 1)
dfmerged.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
0,C0001,Kamd Co,62.0,0.0,Unknown,1.0,1.0,0.0,5.0,0.0,Agency,1005,1,2004-03-01,Office,5,410.71,"$117,564.07",1
1,C0002,Jack Anderson,78.0,1.0,M,1.0,1.0,0.0,5.0,1.0,Website,1002,1,2004-03-01,Office,2,1238.58,"$410,932.67",1
2,C0003,Avah Huang,77.0,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1044,1,2004-06-01,Apartment,44,827.87,"$229,464.71",1
3,C0004,Nora Lynch,77.0,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1043,1,2004-06-01,Apartment,43,1160.36,"$377,313.56",1
4,C0005,Rodolfo Gibson,89.0,1.0,M,1.0,0.0,1.0,2.0,1.0,Website,1033,1,2004-08-01,Apartment,33,1434.09,"$412,856.56",1

In [4]:
dfmerged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         195 non-null    object
 1   full_name          195 non-null    object
 2   age                195 non-null    float64
 3   entity             195 non-null    float64
 4   sex                195 non-null    object
 5   country            195 non-null    float64
 6   state              195 non-null    float64
 7   purpose            195 non-null    float64
 8   deal_satisfaction  195 non-null    float64
 9   mortgage           195 non-null    float64
 10  source             195 non-null    object
 11  id                 267 non-null    int64
 12  building           267 non-null    int64
 13  date_sale          195 non-null    object
 14  type               267 non-null    object
 15  property#          267 non-null    int64
 16  area               267 non-null    float64
 17  price              267 non-null    object
 18  status             267 non-null    int64
dtypes: float64(8), int64(4), object(7)
memory usage: 39.8+ KB

In [5]:
dfmerged['age'] = dfmerged['age'].astype('Int64')
dfmerged.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
0,C0001,Kamd Co,62,0.0,Unknown,1.0,1.0,0.0,5.0,0.0,Agency,1005,1,2004-03-01,Office,5,410.71,"$117,564.07",1
1,C0002,Jack Anderson,78,1.0,M,1.0,1.0,0.0,5.0,1.0,Website,1002,1,2004-03-01,Office,2,1238.58,"$410,932.67",1
2,C0003,Avah Huang,77,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1044,1,2004-06-01,Apartment,44,827.87,"$229,464.71",1
3,C0004,Nora Lynch,77,1.0,F,1.0,1.0,1.0,5.0,0.0,Website,1043,1,2004-06-01,Apartment,43,1160.36,"$377,313.56",1
4,C0005,Rodolfo Gibson,89,1.0,M,1.0,0.0,1.0,2.0,1.0,Website,1033,1,2004-08-01,Apartment,33,1434.09,"$412,856.56",1

In [6]:
cols = ['entity','country','state','purpose','deal_satisfaction','mortgage']
dfmerged[cols] = dfmerged[cols].astype('Int64')
dfmerged.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
0,C0001,Kamd Co,62,0,Unknown,1,1,0,5,0,Agency,1005,1,2004-03-01,Office,5,410.71,"$117,564.07",1
1,C0002,Jack Anderson,78,1,M,1,1,0,5,1,Website,1002,1,2004-03-01,Office,2,1238.58,"$410,932.67",1
2,C0003,Avah Huang,77,1,F,1,1,1,5,0,Website,1044,1,2004-06-01,Apartment,44,827.87,"$229,464.71",1
3,C0004,Nora Lynch,77,1,F,1,1,1,5,0,Website,1043,1,2004-06-01,Apartment,43,1160.36,"$377,313.56",1
4,C0005,Rodolfo Gibson,89,1,M,1,0,1,2,1,Website,1033,1,2004-08-01,Apartment,33,1434.09,"$412,856.56",1

In [7]:
dfmerged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         195 non-null    object
 1   full_name          195 non-null    object
 2   age                195 non-null    Int64
 3   entity             195 non-null    Int64
 4   sex                195 non-null    object
 5   country            195 non-null    Int64
 6   state              195 non-null    Int64
 7   purpose            195 non-null    Int64
 8   deal_satisfaction  195 non-null    Int64
 9   mortgage           195 non-null    Int64
 10  source             195 non-null    object
 11  id                 267 non-null    int64
 12  building           267 non-null    int64
 13  date_sale          195 non-null    object
 14  type               267 non-null    object
 15  property#          267 non-null    int64
 16  area               267 non-null    float64
 17  price              267 non-null    object
 18  status             267 non-null    int64
dtypes: Int64(7), float64(1), int64(4), object(7)
memory usage: 41.6+ KB

In [8]:
dfmerged['property#'].nunique()

59

In [9]:
dfmerged['price'].max()

'$538,271.74 '

In [10]:
dfmerged['price'].min()

'$117,564.07 '

In [11]:
dfmerged['entity']

0         0
1         1
2         1
3         1
4         1
       ...
262    <NA>
263    <NA>
264    <NA>
265    <NA>
266    <NA>
Name: entity, Length: 267, dtype: Int64

In [12]:
#basic statistical insights regarding payment types, prices, and status
data = dfmerged[['entity','purpose','deal_satisfaction', 'price', 'mortgage','status']]
list_prop = pd.DataFrame(data, index = dfmerged['building'])
list_prop

          entity  purpose  deal_satisfaction         price  mortgage  status
building
1              1        0                  5  $410,932.67          1       1
1              1        0                  5  $410,932.67          1       1
1              1        0                  5  $410,932.67          1       1
1              1        0                  5  $410,932.67          1       1
1              1        0                  5  $410,932.67          1       1
...          ...      ...                ...           ...       ...     ...
5              1        1                  2  $207,581.43          1       1
5              1        1                  2  $207,581.43          1       1
5              1        1                  2  $207,581.43          1       1
5              1        1                  2  $207,581.43          1       1
5              1        1                  2  $207,581.43          1       1

[267 rows x 6 columns]

In [13]:
list_prop['mortgage'].unique()

<IntegerArray>
[1, 0]
Length: 2, dtype: Int64

In [14]:
dfmerged['status'].value_counts()

status
1    195
0     72
Name: count, dtype: int64

In [15]:
dfmerged['status'].sum()

195

In [16]:
list_prop['status'].sum()

267

In [17]:
list_prop['status'].value_counts()

status
1    267
Name: count, dtype: int64

In [18]:
list_prop = dfmerged[['entity', 'purpose', 'deal_satisfaction','area', 'price', 'mortgage', 'status']].copy()
list_prop

,entity,purpose,deal_satisfaction,area,price,mortgage,status
0,0,0,5,410.71,"$117,564.07",0,1
1,1,0,5,1238.58,"$410,932.67",1,1
2,1,1,5,827.87,"$229,464.71",0,1
3,1,1,5,1160.36,"$377,313.56",0,1
4,1,1,2,1434.09,"$412,856.56",1,1
...,...,...,...,...,...,...,...
262,<NA>,<NA>,<NA>,1238.58,"$322,610.74",<NA>,0
263,<NA>,<NA>,<NA>,794.52,"$279,191.26",<NA>,0
264,<NA>,<NA>,<NA>,1013.27,"$287,996.53",<NA>,0
265,<NA>,<NA>,<NA>,1074.71,"$365,868.78",<NA>,0
266,<NA>,<NA>,<NA>,789.25,"$199,216.40",<NA>,0

In [19]:
#establishing building type as index
list_prop.index = dfmerged['building']
list_prop

,entity,purpose,deal_satisfaction,area,price,mortgage,status
building,,,,,,,
1,0,0,5,410.71,"$117,564.07",0,1
1,1,0,5,1238.58,"$410,932.67",1,1
1,1,1,5,827.87,"$229,464.71",0,1
1,1,1,5,1160.36,"$377,313.56",0,1
1,1,1,2,1434.09,"$412,856.56",1,1
...,...,...,...,...,...,...,...
5,<NA>,<NA>,<NA>,1238.58,"$322,610.74",<NA>,0
5,<NA>,<NA>,<NA>,794.52,"$279,191.26",<NA>,0
5,<NA>,<NA>,<NA>,1013.27,"$287,996.53",<NA>,0
5,<NA>,<NA>,<NA>,1074.71,"$365,868.78",<NA>,0
5,<NA>,<NA>,<NA>,789.25,"$199,216.40",<NA>,0

In [20]:
list_prop.loc[:,'deal_satisfaction']

building
1       5
1       5
1       5
1       5
1       2
     ...
5    <NA>
5    <NA>
5    <NA>
5    <NA>
5    <NA>
Name: deal_satisfaction, Length: 267, dtype: Int64

In [21]:
list_prop.loc[:,'deal_satisfaction'].value_counts()

deal_satisfaction
5    69
4    42
3    40
2    25
1    19
Name: count, dtype: Int64

In [22]:
list_prop.groupby('building')['deal_satisfaction'].value_counts()

building  deal_satisfaction
1         5                    24
          1                     8
          2                     6
          3                     5
          4                     3
2         5                    17
          3                    12
          4                    12
          2                     8
          1                     5
3         3                    16
          4                    14
          5                    14
          2                     6
          1                     3
4         5                     9
          4                     7
          3                     4
          1                     2
          2                     1
5         4                     6
          5                     5
          2                     4
          3                     3
          1                     1
Name: count, dtype: Int64

In [23]:
list_prop.groupby('building')['price'].value_counts()

building  price
1         $117,564.07     1
          $163,162.88     1
          $179,674.08     1
          $189,194.31     1
          $191,389.87     1
                         ..
5         $390,494.27     1
          $396,330.29     1
          $413,761.71     1
          $448,574.67     1
          $532,877.38     1
Name: count, Length: 266, dtype: int64

In [24]:
#is there a building type-price relationship? 
list_prop.loc[5].groupby('building')['price'].value_counts()

building  price
5         $147,343.69     1
          $153,466.71     1
          $165,430.28     1
          $175,773.59     1
          $188,743.11     1
          $195,874.94     1
          $199,216.40     1
          $199,730.73     1
          $211,406.87     1
          $212,644.39     1
          $212,916.36     1
          $219,252.89     1
          $223,577.32     1
          $227,072.88     1
          $228,410.05     1
          $230,216.22     1
          $230,943.38     1
          $234,032.88     1
          $234,750.59     1
          $237,680.88     1
          $240,539.35     1
          $249,591.99     1
          $250,415.38     1
          $252,053.03     1
          $255,337.90     1
          $261,742.74     1
          $263,123.42     1
          $264,011.70     1
          $269,075.30     1
          $271,227.49     1
          $273,165.58     1
          $276,323.87     1
          $278,575.87     1
          $279,191.26     1
          $286,433.57     1
          $287,466.41     1
          $287,996.53     1
          $308,660.80     1
          $315,382.11     1
          $322,610.74     1
          $338,472.13     1
          $338,482.45     1
          $349,865.22     1
          $351,304.58     1
          $357,538.20     1
          $365,868.78     1
          $372,016.56     1
          $390,494.27     1
          $396,330.29     1
          $413,761.71     1
          $448,574.67     1
          $532,877.38     1
Name: count, dtype: int64

In [25]:
list_prop.loc[1].groupby('building')['price'].value_counts()

building  price
1         $117,564.07     1
          $163,162.88     1
          $179,674.08     1
          $189,194.31     1
          $191,389.87     1
          $193,660.62     1
          $196,220.05     1
          $198,841.70     1
          $204,027.09     1
          $204,434.68     1
          $206,445.42     1
          $206,958.71     1
          $207,581.43     1
          $208,930.81     1
          $210,745.17     1
          $215,410.28     1
          $217,787.71     1
          $218,585.92     1
          $219,630.90     1
          $222,947.21     1
          $224,076.84     1
          $229,464.71     1
          $234,172.39     1
          $235,762.34     1
          $238,811.06     1
          $239,341.58     1
          $244,624.87     1
          $246,050.40     1
          $246,172.68     1
          $246,331.90     1
          $248,525.12     1
          $250,312.53     1
          $261,579.89     1
          $264,142.16     1
          $265,467.68     1
          $276,759.18     1
          $300,385.62     1
          $317,196.40     1
          $317,473.86     1
          $331,154.88     1
          $377,313.56     1
          $382,041.13     1
          $398,903.42     1
          $400,865.92     1
          $401,302.82     1
          $410,932.67     1
          $412,856.56     1
          $432,679.91     1
          $448,134.27     1
          $467,083.31     1
          $480,545.81     1
          $503,790.23     1
Name: count, dtype: int64

In [26]:
list_prop.groupby('building')['status'].value_counts()

building  status
1         1         46
          0          6
2         1         54
          0          3
3         1         53
          0         10
4         1         23
          0         20
5         0         33
          1         19
Name: count, dtype: int64

In [27]:
list_prop.groupby('building')['mortgage'].value_counts()

building  mortgage
1         0           32
          1           14
2         0           36
          1           18
3         0           38
          1           15
4         0           14
          1            9
5         0           13
          1            6
Name: count, dtype: Int64

In [28]:
list_prop.groupby('status')['mortgage'].value_counts()

status  mortgage
1       0           133
        1            62
Name: count, dtype: Int64

In [29]:
#there aren't many buildings being sold with mortgages
list_prop.groupby('mortgage')['purpose'].value_counts()
#more buildings for personal homes are sold with mortgage plans
#whereas buildings used for companies are less often dependent on such

mortgage  purpose
0         1          71
          0          62
1         1          48
          0          14
Name: count, dtype: Int64

In [30]:
list_prop.groupby('building')['status'].mean()

building
1    0.884615
2    0.947368
3    0.841270
4    0.534884
5    0.365385
Name: status, dtype: float64

In [31]:
list_prop.groupby('building')['mortgage'].mean()

building
1    0.304348
2    0.333333
3    0.283019
4    0.391304
5    0.315789
Name: mortgage, dtype: Float64

In [32]:
list_prop['price'] = list_prop['price'].str.strip()
list_prop['price'] = list_prop['price'].str.replace('$','')
list_prop['price'] = list_prop['price'].str.replace(',','')
list_prop['price'] = list_prop['price'].astype('Float64')
list_prop.groupby('building')['price'].mean().round()

building
1    275143.0
2    286662.0
3    280451.0
4    290240.0
5    274558.0
Name: price, dtype: Float64

In [33]:
list_prop.groupby('status')['price'].mean().round()

status
0    312961.0
1    269435.0
Name: price, dtype: Float64

In [34]:
list_prop.groupby('mortgage')['price'].mean().round()

mortgage
0    267253.0
1    274114.0
Name: price, dtype: Float64

In [35]:
list_prop.groupby('purpose')['price'].mean().round()

purpose
0    252347.0
1    280347.0
Name: price, dtype: Float64

In [36]:
list_prop.groupby('area')['price'].mean().round()
#there is a relationship between area and price

area
410.71     117564.0
579.75     171263.0
587.28     189220.0
598.58     175774.0
606.33     147344.0
             ...
1608.84    496266.0
1611.85    502890.0
1615.29    472962.0
1769.48    532877.0
1942.50    503790.0
Name: price, Length: 97, dtype: Float64

In [37]:
list_prop2 = dfmerged[['building','country','state', 'purpose','area','price', 'status','deal_satisfaction']].copy()
list_prop2.index = dfmerged['purpose']

In [38]:
list_prop2

,building,country,state,purpose,area,price,status,deal_satisfaction
purpose,,,,,,,,
0,1,1,1,0,410.71,"$117,564.07",1,5
0,1,1,1,0,1238.58,"$410,932.67",1,5
1,1,1,1,1,827.87,"$229,464.71",1,5
1,1,1,1,1,1160.36,"$377,313.56",1,5
1,1,1,0,1,1434.09,"$412,856.56",1,2
...,...,...,...,...,...,...,...,...
<NA>,5,<NA>,<NA>,<NA>,1238.58,"$322,610.74",0,<NA>
<NA>,5,<NA>,<NA>,<NA>,794.52,"$279,191.26",0,<NA>
<NA>,5,<NA>,<NA>,<NA>,1013.27,"$287,996.53",0,<NA>
<NA>,5,<NA>,<NA>,<NA>,1074.71,"$365,868.78",0,<NA>
<NA>,5,<NA>,<NA>,<NA>,789.25,"$199,216.40",0,<NA>

In [39]:
list_prop2['country'].sum()

177

In [40]:
list_prop2.groupby('country')['status'].sum()
#most of the operations have taken place in the USA

country
0     18
1    177
Name: status, dtype: int64

In [41]:
list_prop2.groupby('state')['status'].sum()
#within the USA, the majority has taken place in California

state
0     75
1    120
Name: status, dtype: int64

In [42]:
list_prop2.groupby('state')['status'].sum()/195

state
0    0.384615
1    0.615385
Name: status, dtype: float64

In [43]:
list_prop2.groupby('country')['status'].sum()/(177+18)
#USA leads the dataset with 90% of the market 
#state wise, there is a clear stability in the Californian market
#and a solid 40% in all other states, with growth potential short-term

country
0    0.092308
1    0.907692
Name: status, dtype: float64

In [44]:
list_prop2['price'] = list_prop2['price'].str.strip()
list_prop2['price'] = list_prop2['price'].str.replace('$','')
list_prop2['price'] = list_prop2['price'].str.replace(',','')
list_prop2['price'] = list_prop2['price'].astype('Float64')

list_prop2.groupby('country').sum()

,building,state,purpose,area,price,status,deal_satisfaction
country,,,,,,,
0,44,2,4,16033.47,4732700.2,18,68
1,456,118,115,159440.62,47807039.18,177,634

In [45]:
list_prop2.groupby('country')['status'].sum()
#most properties sold in other countries are with purposes of investment, not homes
#if the goal is to explore the global market, especially in Europe, there should be a focus on investments more than homes

country
0     18
1    177
Name: status, dtype: int64

In [46]:
dfmerged['type'].unique()

array(['Office', 'Apartment'], dtype=object)

In [47]:
dfmerged1 = dfmerged

In [48]:
dfmerged1['type'] = pd.get_dummies(dfmerged1['type'],drop_first = True, dtype = int)
dfmerged1['type'].unique()

array([1, 0])

In [49]:
dfmerged1.groupby('country')['type'].sum()

country
0    0
1    7
Name: type, dtype: int64

In [50]:
dfmerged1.groupby('type')['country'].sum()

type
0    170
1      7
Name: country, dtype: Int64

In [51]:
dfmerged1.head()
#out of 18 sales in the global market, 7 were for offices, whereas 11 were apartments
#yet, only 4 were for homes
#so there is still primacy in investments

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
0,C0001,Kamd Co,62,0,Unknown,1,1,0,5,0,Agency,1005,1,2004-03-01,1,5,410.71,"$117,564.07",1
1,C0002,Jack Anderson,78,1,M,1,1,0,5,1,Website,1002,1,2004-03-01,1,2,1238.58,"$410,932.67",1
2,C0003,Avah Huang,77,1,F,1,1,1,5,0,Website,1044,1,2004-06-01,0,44,827.87,"$229,464.71",1
3,C0004,Nora Lynch,77,1,F,1,1,1,5,0,Website,1043,1,2004-06-01,0,43,1160.36,"$377,313.56",1
4,C0005,Rodolfo Gibson,89,1,M,1,0,1,2,1,Website,1033,1,2004-08-01,0,33,1434.09,"$412,856.56",1

In [52]:
#relationship between age and properties
dfmerged1['age'].max()

94

In [53]:
dfmerged1['age'].min()

39

In [54]:
years_since_sale = (pd.Timestamp.today() - pd.to_datetime(dfmerged['date_sale'])).dt.days / 365.25
years_since_sale

0      21.938398
1      21.938398
2      21.686516
3      21.686516
4      21.519507
         ...
262          NaN
263          NaN
264          NaN
265          NaN
266          NaN
Name: date_sale, Length: 267, dtype: float64

In [55]:
dfmerged1['age_at_sale'] = dfmerged1['age'] - years_since_sale.round()
dfmerged1.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status,age_at_sale
0,C0001,Kamd Co,62,0,Unknown,1,1,0,5,0,Agency,1005,1,2004-03-01,1,5,410.71,"$117,564.07",1,40.0
1,C0002,Jack Anderson,78,1,M,1,1,0,5,1,Website,1002,1,2004-03-01,1,2,1238.58,"$410,932.67",1,56.0
2,C0003,Avah Huang,77,1,F,1,1,1,5,0,Website,1044,1,2004-06-01,0,44,827.87,"$229,464.71",1,55.0
3,C0004,Nora Lynch,77,1,F,1,1,1,5,0,Website,1043,1,2004-06-01,0,43,1160.36,"$377,313.56",1,55.0
4,C0005,Rodolfo Gibson,89,1,M,1,0,1,2,1,Website,1033,1,2004-08-01,0,33,1434.09,"$412,856.56",1,67.0

In [56]:
dfmerged1['age_at_sale'].min()

19.0

In [57]:
dfmerged1['age_at_sale'].max()

75.0

In [58]:
df_sold = dfmerged1[dfmerged1['status'] == 1]
df_sold['price_bin'] = pd.cut(dfmerged1['price'], bins = 10)
df_sold['age_bin'] = pd.cut(dfmerged1['age_at_sale'],bins = 10)
df_sold

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U12'), dtype('float64')) -> None

In [ ]:
cum_age = df_sold['age_bin'].value_counts().sort_index().cumsum()
cum_price = df_sold['price_bin'].value_counts().sort_index().cumsum()
cum_age

In [ ]:
cum_price

In [ ]:
freq_table = pd.crosstab(df_sold['age_bin'],df_sold['price_bin'])
cum_freq_by_price = freq_table.cumsum(axis=0)
cum_freq_by_price

In [ ]:
corr = df_sold[['age_at_sale','price']].corr()
corr
#The Pearson correlation coefficient between age at sale and property price is -0.155, 
#indicating a very weak negative linear relationship. This suggests that as age increases, 
#property prices tend to decrease slightly, but the relationship is not strong.

In [ ]:
cov = df_sold[['age_at_sale','price']].cov()
cov

In [ ]:
#confirming the negative relation between age and price: as age increases,
#prices decrease. Perhaps, this is due to taking less risks at an older age,
#a change of priorities, or more informed decisions as to what it is needed.

In [ ]:
#However, these results are tricky: the cumulative frequency table by price shows that middle-age groups
#buy more properties(therefore they are the main clientele), whereas younger groups or older
#tend to buy less properties. This tells us that withing each age group, purchases accumulate
#gradually across price bins, meaning that more expensive properties are more common
#among middle-aged buyers.

In [ ]:
list_prop2.head()

In [ ]:
list_prop2.groupby('deal_satisfaction')['country'].value_counts()

In [ ]:
list_prop2.groupby('deal_satisfaction')['state'].value_counts()

In [ ]:
average_price_building = list_prop2.groupby('building')['price'].mean()
average_price_building

In [ ]:
average_area_building = list_prop2.groupby('building')['area'].mean()
average_area_building

In [ ]:
average_sat_building = list_prop2.groupby('building')['deal_satisfaction'].mean()
average_sat_building

In [ ]:
average_sat_country = list_prop2.groupby('country')['deal_satisfaction'].mean()
average_sat_country

In [ ]:
average_sat_state = list_prop2.groupby('state')['deal_satisfaction'].mean()
average_sat_state

In [ ]:
average_price_state = list_prop2.groupby('state')['price'].mean()
average_price_state

In [ ]:
country_freq = list_prop2['country'].value_counts()
country_freq

In [ ]:
state_freq = list_prop2['state'].value_counts()
state_freq

In [ ]:
rel_state = state_freq / state_freq.sum()
rel_country = country_freq / country_freq.sum()

In [ ]:
cum_freq_state = rel_state.sort_values(ascending= False).cumsum()
cum_freq_state

In [ ]:
state_table = pd.DataFrame({
    'Frequency': state_freq,
    'Relative Frequency': rel_state,
    'Cumulative Frequency': cum_freq_state
})

state_table

In [ ]:
country_cumfreq = rel_country.sort_values(ascending = False).cumsum()
country_cumfreq

In [ ]:
country_table = pd.DataFrame({
    'Frequency': country_freq,
    'Relative Frequency': rel_country,
    'Cumulative Frequency': country_cumfreq
})

country_table

In [ ]:
avg_by_building = list_prop2.groupby('building').agg({
    'price': 'mean',
    'area': 'mean',
    'deal_satisfaction': 'mean'
})

avg_by_building

In [ ]:
avg_by_building.to_csv('avg_by_building.csv')

In [ ]:
country_table.to_csv('country_table.csv')

In [ ]:
state_table.to_csv('state_table.csv')

In [ ]:
age_price_corr = corr
age_price_corr.to_csv('age_price_corr.csv')

In [ ]:
age_price_cov = cov
age_price_cov.to_csv('age_price_cov.csv')

In [ ]:
cum_freq_by_price.to_csv('cum_freq_by_price.csv')

In [ ]:
df_sold.to_csv('df_sold.csv')

In [ ]:
dfmerged1.to_csv('dfmerged1.csv')

In [ ]:
avg_by_country = list_prop2.groupby('country').agg(
    avg_price=('price', 'mean'),
    avg_area=('area', 'mean'),
    avg_deal_satisfaction=('deal_satisfaction', 'mean')
)

avg_by_country

In [ ]:
avg_by_country.to_csv('avg_country.csv')

In [ ]:
avg_by_state = list_prop2.groupby('state').agg(
    avg_price=('price', 'mean'),
    avg_area=('area', 'mean'),
    avg_deal_satisfaction=('deal_satisfaction', 'mean')
)

avg_by_state